# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mozilla-PromptService
version:      0.04
version_from: lib/Mozilla/PromptService.pm
installdirs:  site
requires:
    Mozilla::ConsoleService:       0.04
    Mozilla::DOM:                  0.21
    Mozilla::Mechanize:            0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
